### ISSUE TITLE
[PKG-REQ] FFTW 3.3.9

### ISSUE THREAD

**Issue by p-costa** [IRHPC/irhpc.github.io#10]
**Information**
- Package Name :: FFTW3
- Site :: [fftw.org](http://www.fftw.org/)
- Installation instructions (generic) :: would be nice to configure it with `--enable-threads` to allow for shared-memory parallelism; perhaps some users may also want it to be built with `--enable-mpi` to leverage FFTW's distributed-memory FFTs

**Comment by eojons** [comment]
FFTW/3.3.10-gompi-2021b available as part of libsci-gcc
